### ISSUE TITLE
v6 support

### ISSUE THREAD

**Issue by df7cb** [oftc/node-ircws#2]
At the moment it seems we can't bind to v6.

**Comment by dwfreed** [comment]
_Disclaimer: I don't really know anything about node.js; this is just from some docs reading, and my understanding of how socket listening is usually implemented_

Looking at the docs, the way that net.server.listen() works, if you specify the IPv6 any address (ie, `::`), it seems like it would listen with ipv6only off, which would conflict with existing IPv4 any listeners, throwing `EADDRINUSE`.  I'm not sure how the code would handle only having IPv6 any listeners (whether it would use IPv4-mapped IPv6 addresses for client remote addresses or straight IPv4 addresses), but another solution would be to specify the IPv6 address you want to listen on, rather than using the any address.
